name: Validate compilation on Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Swift Setup
      uses: YOCKOW/Action-setup-swift@v1.1.0
      with:
        swift-version: '5.2.2'
    - name: Build
      run:
        make
    - name: Test
      run:
        make test
